public class calc1 {
     //Mandatory. access modifiers { Public, private,global, protected}
//Optional. definition modifiers { virtual,abstract, with sharing, without sharing} 
//Class name is mandatory.
        //public integer 
       /* public Decimal void sum(Integer a, Integer b)
        {
            system.debug('Sum of 2 numbers '+(a+b));
            
        }
*/
    
       public Static Decimal  sum(Integer a, Integer b) {
        return a + b;
    }
    public Static Decimal  subt(Integer a, Integer b) {
        return a - b;
    }
    public Static Decimal  mult(Integer a, Integer b) {
        return a * b;
    }
    public Static Decimal  div(Integer a, Integer b) {
        return a / b;
    }
}